version: "2"

run:
  timeout: 3m

linters:
  default: none
  enable:
    - errcheck
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    paths:
      - gen

formatters:
  enable:
    - gofmt
  exclusions:
    paths:
      - gen
