run:
  timeout: 3m
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - gosec
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - gen
